name: 'w3name action'
description: 'Publish your app names to w3name service'
author: 'pawanpaudel93'
inputs:
  cid:
    required: true
    description: 'IPFS content Id (cid)'
  signing_key:
    required: true
    description: 'w3name signing key to publish names'
  outputs:
    name:
      description: 'IPNS name'
runs:
  using: 'node16'
  main: 'dist/index.js'
